import config from "../../config/config.js";
import { prisma } from "../../lib/prisma.js";
import Stripe from "stripe";
import express, { Router, Request, Response } from "express";

// Services
import {
  markChargePaidService,
  markChargeFailedService,
  createChargeService,
} from "../../services/charges.services.js";
import { ChargeStatus, StudentPlanStatus } from "@prisma/client";

import {
  cancelStudentPlanService,
  upsertStudentPlanBasedOnSubscriptionService,
  upsertStudentPlanBasedOnPaymentIntentService,
} from "../../services/studentplans.services.js";
import { recomputeStudentActiveFlag } from "../../services/students.services.js";

const stripe = new Stripe(config.STRIPE_API_KEY);
const router: Router = express.Router();

router.post(
  "/stripe/connect",
  express.raw({ type: "application/json" }),
  async (req: Request, res: Response) => {
    let event: Stripe.Event;

    // Verifica assinatura do Stripe (ideal: usar um secret dedicado para Connect, ex.: STRIPE_CONNECT_WEBHOOK_SECRET)
    try {
      const signature = req.headers["stripe-signature"] as string;
      event = stripe.webhooks.constructEvent(
        req.body,
        signature,
        // Trocar para config.STRIPE_CONNECT_WEBHOOK_SECRET quando configurar um endpoint dedicado de Connect
        config.STRIPE_WEBHOOK_SECRET,
      );
    } catch (err: any) {
      console.error(
        "[CONNECT-Webhook] Signature verification failed:",
        err.message,
      );
      return res.sendStatus(400);
    }

    try {
      // Em webhooks de Connect, o ID da conta conectada vem em event.account
      const connectAccountId = (event as any)?.account as string | undefined;

      switch (event.type) {
        /**
         * ==========================================
         * PAGAMENTOS AVULSOS (one-time)
         * ==========================================
         */
        case "payment_intent.succeeded": {
          const stripePaymentIntent = event.data.object as Stripe.PaymentIntent;

          // Ignora se for recorrente
          if (!(stripePaymentIntent?.metadata?.payment_type === "one_time")) {
            console.log(
              "[STRIPE-CONNECT-WEBHOOK] Payment_intent was generated by a subscription, ignoring...",
            );
            break;
          }

          const { studentId, userPlanId, userId } =
            stripePaymentIntent.metadata || {};
          if (!studentId || !userPlanId || !userId) break;

          // Idempotência
          const existing = await prisma.charge.findFirst({
            where: { externalId: stripePaymentIntent.id },
          });
          if (existing) break;

          await prisma.$transaction(async (tx) => {
            const charge = await createChargeService(tx, {
              studentId,
              status: ChargeStatus.PAID,
              amount: stripePaymentIntent.amount,
              externalId: stripePaymentIntent.id,
              description:
                stripePaymentIntent.description ??
                "charge generated via payment_intent_succeeded",
              paidAt: new Date(),
            });

            // Cria StudentPlan para compra avulsa
            const studentPlan =
              await upsertStudentPlanBasedOnPaymentIntentService(
                tx,
                { studentId, userPlanId },
                userId,
                stripePaymentIntent,
              );

            // Vincula a Charge ao plano criado
            await tx.charge.update({
              where: { id: charge.id },
              data: { studentPlanId: studentPlan.id },
            });

            await recomputeStudentActiveFlag(tx, studentId);
          });

          break;
        }

        case "customer.subscription.created": {
          const stripeSubscription = event.data.object as Stripe.Subscription;
          const { studentId, userPlanId, userId } =
            stripeSubscription.metadata || {};
          if (!studentId || !userPlanId || !userId) {
            console.log("[CONNECT-Webhook] Missing subscription metadata");
          }
          await prisma.$transaction(async (tx) => {
            await upsertStudentPlanBasedOnSubscriptionService(
              tx,
              { studentId, userPlanId },
              userId,
              stripeSubscription,
            );

            await recomputeStudentActiveFlag(tx, studentId);
          });

          break;
        }

        case "customer.subscription.updated": {
          const stripeSubscription = event.data.object as Stripe.Subscription;
          const { studentId, userPlanId, userId } =
            stripeSubscription.metadata || {};
          if (!studentId || !userPlanId || !userId) {
            console.log("[CONNECT-Webhook] Missing subscription metadata");
          }
          await prisma.$transaction(async (tx) => {
            await upsertStudentPlanBasedOnSubscriptionService(
              tx,
              { studentId, userPlanId },
              userId,
              stripeSubscription,
            );

            await recomputeStudentActiveFlag(tx, studentId);
          });
          break;
        }
        case "customer.subscription.deleted": {
          const stripeSubscription = event.data.object as Stripe.Subscription;
          const { studentId, userPlanId, userId } =
            stripeSubscription.metadata || {};
          if (!studentId || !userPlanId || !userId) {
            console.log("[CONNECT-Webhook] Missing subscription metadata");
          }

          await prisma.$transaction(async (tx) => {
            const studentPlan = await tx.studentPlan.findFirstOrThrow({
              where: {
                studentId,
                userPlanId,
                stripeId: stripeSubscription.id,
              },
              select: {
                id: true,
              },
            });
            await cancelStudentPlanService(tx, studentPlan!.id, userId);
            await recomputeStudentActiveFlag(tx, studentId);
          });
          break;
        }

        case "invoice.paid": {
          const invoice = event.data.object as Stripe.Invoice;
          if (
            invoice.billing_reason === "subscription_create" ||
            invoice.billing_reason === "subscription_cycle"
          ) {
            // Recupera subscription para metadata
            const subscriptionId =
              typeof invoice.parent?.subscription_details?.subscription ===
              "string"
                ? invoice.parent?.subscription_details?.subscription
                : (
                    invoice.parent?.subscription_details
                      ?.subscription as Stripe.Subscription
                  ).id;

            const subscription = await stripe.subscriptions.retrieve(
              subscriptionId,
              {
                ...(connectAccountId
                  ? { stripeAccount: connectAccountId }
                  : {}),
              },
            );

            const { studentId, userPlanId, userId } =
              subscription.metadata || {};
            if (!studentId || !userPlanId || !userId) {
              console.log(
                "[CONNECT-Webhook] Subscription metadata missing, ignoring invoice:",
                invoice.id,
              );
              break;
            }
            await prisma.$transaction(async (tx) => {
              await createChargeService(tx, {
                studentId,
                status: ChargeStatus.PAID,
                amount: subscription.items?.data?.[0]?.price?.unit_amount ?? 0,
                externalId: invoice.id,
                description: "Fatura recorrente criada (via invoice.paid)",
                paidAt: new Date(),
              });

              await recomputeStudentActiveFlag(tx, studentId);
            });
          }
          break;
        }

        case "invoice.payment_failed": {
          const invoice = event.data.object as Stripe.Invoice;
          // Recupera subscription para metadata
          const subscriptionId =
            typeof invoice.parent?.subscription_details?.subscription ===
            "string"
              ? invoice.parent?.subscription_details?.subscription
              : (
                  invoice.parent?.subscription_details
                    ?.subscription as Stripe.Subscription
                ).id;

          const subscription = await stripe.subscriptions.retrieve(
            subscriptionId,
            {
              ...(connectAccountId ? { stripeAccount: connectAccountId } : {}),
            },
          );

          const { studentId, userPlanId, userId } = subscription.metadata || {};
          if (!studentId || !userPlanId || !userId) {
            console.log(
              "[CONNECT-Webhook] Subscription metadata missing, ignoring invoice:",
              invoice.id,
            );
            break;
          }
          await prisma.$transaction(async (tx) => {
            const charge = await tx.charge.findFirstOrThrow({
              where: {
                OR: [
                  { externalId: subscriptionId },
                  { externalId: invoice.id },
                ],
              },
              select: {
                id: true,
              },
            });
            await markChargeFailedService(tx, charge.id);
            await recomputeStudentActiveFlag(tx, studentId);
          });
        }
        default:
          console.log(
            "[CONNECT-Webhook] Event received but ignored:",
            event.type,
          );
      }

      return res.sendStatus(200);
    } catch (err) {
      console.error("[CONNECT-Webhook] Error:", err);
      return res.sendStatus(500);
    }
  },
);

export default router;
